<template>
    <b-container>
        <h1>API</h1>
        <p>
            Všetky údaje, ktoré sú zobrazené na tejto stránke, plus ďalšie, sú dostupné prostredníctvom <a href="https://" target="_blank">GraphQL API</a>. Na danej URL nájdete aj GraphiQL browser, ktorý poskytuje základnú dokumentáciu k jednotlivým dátovým typom. Dôkladnejšiu dokumentáciu zatiaľ nemáme.
        </p>
        <p>
            Použitie nie je nijako obmedzené, ak však plánujete realizovať časté a hromadné prístupy k API, tak sa nám vopred ozvite, aby sme našli udržateľné riešenie pre obe strany.
        </p>
        <h2>Dátové typy a ich stav</h2>
        <table>
            <tr>
                <th>Typ</th><th>Stav</th><th>Poznámka</th>
            </tr>
            <tr>
                <td>PersonType</td><td>Stabilný</td><td>Môže byť rozšírený o nové vlastnosti</td>
            </tr>
            <tr>
                <td>VillageType</td><td>Hotovo</td><td></td>
            </tr>
            <tr>
                <td>DistrictType</td><td>Hotovo</td><td></td>
            </tr>
            <tr>
                <td>RegionType</td><td>Hotovo</td><td></td>
            </tr>
            <tr>
                <td>MemberType</td><td>Stabilný</td><td></td>
            </tr>
            <tr>
                <td>PeriodType</td><td>Hotovo</td><td></td>
            </tr>
            <tr>
                <td>PartyType</td><td></td><td></td>
            </tr>
            <tr>
                <td>ClubMemberType</td><td>Hotovo</td><td></td>
            </tr>
            <tr>
                <td>ClubType</td><td>Stabilný</td><td></td>
            </tr>
            <tr>
                <td>VotingVoteType</td><td>Hotovo</td><td></td>
            </tr>
            <tr>
                <td>VotingType</td><td>Hotovo</td><td></td>
            </tr>
            <tr>
                <td>SessionType</td><td></td><td></td>
            </tr>
            <tr>
                <td>SessionProgramPointType</td><td></td><td></td>
            </tr>
            <tr>
                <td>PressType</td><td></td><td></td>
            </tr>
            <tr>
                <td>BillType</td><td></td><td></td>
            </tr>
            <tr>
                <td>DebateAppearanceType</td><td></td><td></td>
            </tr>
            <tr>
                <td>InterpellationType</td><td></td><td></td>
            </tr>
            <tr>
                <td>AmendmentType</td><td></td><td></td>
            </tr>
            <tr>
                <td>AmendmentSignedMemberType</td><td></td><td></td>
            </tr>
            <tr>
                <td>AmendmentSubmitterType</td><td></td><td></td>
            </tr>
            <tr>
                <td>BillProcessStepType</td><td></td><td></td>
            </tr>
            <tr>
                <td>ClubStatsType</td><td>Stabilný</td><td></td>
            </tr>
            <tr>
                <td>MemberStatsType</td><td>Stabilný</td><td></td>
            </tr>
        </table>
    </b-container>
</template>

<script>
export default {
    name: 'API',
};
</script>
