import gql from 'graphql-tag';

export const allAmendmentsQuery = gql`
    query allAmendments($clubId: ID, $submitter: ID, $first:Int!, $after: String, $orderBy: [String]) {
        allAmendments(club:$clubId, submitters: [$submitter], first:$first, after:$after, orderBy:$orderBy) {
            totalCount
            pageInfo {
                hasNextPage
                hasPreviousPage
                startCursor
                endCursor
            }
            edges {
                node {
                    id
                    date
                    externalId
                    press {
                        id
                        title
                    }
                }
            }
        }
    }
`
