import gql from 'graphql-tag';

export const AllClubsQuery = gql`
query allClubs($periodNum:ID!) {
    allClubs(period_PeriodNum:$periodNum) {
        edges {
            node {
                id
                name
                currentMemberCount
                coalition
            }
        }
    }
}
`