import gql from 'graphql-tag';

export const VotingQuery = gql`
query voting($id: ID!) {
    voting(id: $id) {
        topic
        session {
            id
            name
        }
        press {
            id
            pressNum
        }
        result
        timestamp
        url
        chartSeries {
            labels
            series
        }
    }
}
`
